---
  - import_tasks: 3.4/jobs-build-dependencies.yml
  - import_tasks: 3.4/jobs-dependencies.yml
  - import_tasks: 3.4/jobs-unittest.yml
  - import_tasks: 18.10/jobs-build-dependencies.yml
  - import_tasks: 18.10/jobs-dependencies.yml
  - import_tasks: 18.10/jobs-unittest.yml
  - import_tasks: 19.04/jobs-build-dependencies.yml
  - import_tasks: 19.04/jobs-dependencies.yml
  - import_tasks: 19.04/jobs-unittest.yml
  - import_tasks: 19.04/jobs-stable.yml
  - import_tasks: 19.10/jobs-build-dependencies.yml
  - import_tasks: 19.10/jobs-dependencies.yml
  - import_tasks: 19.10/jobs-unittest.yml
  - import_tasks: 19.10/jobs-stable.yml
  - import_tasks: 19.10/jobs-misc.yml
  - import_tasks: 20.04/jobs-build-dependencies.yml
  - import_tasks: 20.04/jobs-dependencies.yml
  - import_tasks: 20.04/jobs-unittest.yml
  - import_tasks: 20.04/jobs-stable.yml
  - import_tasks: 20.04/jobs-misc.yml
